# Generated by Django 5.2.7 on 2025-10-04 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podpicker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("hash", models.CharField()),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
                ("imageUrl", models.URLField()),
                ("audioUrl", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="PodcastSeries",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("hash", models.CharField()),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("imageUrl", models.URLField()),
                ("genres", models.TextField()),
                ("language", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episodes",
                    models.ManyToManyField(
                        related_name="playlists", to="podpicker.podcastepisode"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="bookmarked_episodes",
            field=models.ManyToManyField(
                related_name="bookmarked_by", to="podpicker.podcastepisode"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="finished_episodes",
            field=models.ManyToManyField(
                related_name="finished_by", to="podpicker.podcastepisode"
            ),
        ),
        migrations.AddField(
            model_name="podcastepisode",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="episodes",
                to="podpicker.podcastseries",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_series",
            field=models.ManyToManyField(
                related_name="blocked_by", to="podpicker.podcastseries"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="followed_series",
            field=models.ManyToManyField(
                related_name="followed_by", to="podpicker.podcastseries"
            ),
        ),
    ]
