# Generated by Django 5.2.7 on 2025-10-04 06:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podpicker", "0002_podcastepisode_podcastseries_playlist_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podcastseries",
            options={"verbose_name_plural": "Podcast series"},
        ),
        migrations.AddField(
            model_name="playlist",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="session",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="podcastseries",
            name="genres",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="blocked_series",
            field=models.ManyToManyField(
                related_name="+", to="podpicker.podcastseries"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bookmarked_episodes",
            field=models.ManyToManyField(
                related_name="+", to="podpicker.podcastepisode"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="finished_episodes",
            field=models.ManyToManyField(
                related_name="+", to="podpicker.podcastepisode"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followed_series",
            field=models.ManyToManyField(
                related_name="+", to="podpicker.podcastseries"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False), ("session__isnull", False), _connector="OR"
                ),
                name="playlist_user_or_session_required",
            ),
        ),
    ]
