# Generated by Django 5.2.7 on 2025-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podpicker", "0003_alter_podcastseries_options_playlist_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podcastseries",
            options={"verbose_name_plural": "podcast series"},
        ),
        migrations.AlterField(
            model_name="podcastepisode",
            name="imageUrl",
            field=models.URLField(null=True),
        ),
    ]
