# Generated by Django 5.2.7 on 2025-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podpicker", "0005_alter_playlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcastepisode",
            name="published",
            field=models.DateTimeField(null=True),
        ),
    ]
