# Generated by Django 5.2.7 on 2025-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podpicker", "0006_podcastepisode_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastseries",
            name="imageUrl",
            field=models.URLField(null=True),
        ),
    ]
