# Generated by Django 5.2.7 on 2025-11-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podpicker", "0007_alter_podcastseries_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastepisode",
            name="hash",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="podcastseries",
            name="hash",
            field=models.CharField(null=True),
        ),
    ]
